### ISSUE TITLE
Только log

### ISSUE THREAD

**Issue by victor-yacovlev** [mipt-proglang-2015/proglangs_morozov#2]
Как начать игру после входа пользователей?

![snapshot3](https://cloud.githubusercontent.com/assets/1440088/11781457/1b09de84-a27b-11e5-8797-2188c6f4a957.png)

**Comment by mls93** [comment]
Надо кликнуть на игрока синего цвета из списка. У него появится табличка
подтверждения, если он согласится, то у обоих игроков появится расширяемое
поле 10х10

**Comment by mls93** [comment]
И да, я всё-таки сделал с минимальной, но хоть какой-то авторизацией(т.е.
открыть в двух аналогичных окнах одного браузера одной браузера разным
пользователям не получится, но можно открыть в приватном и неприватном
окнах - я это так и тестировал)
